version: "1.0"
services:
  postgres:
    container_name: brainydocs
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: brainydocs
      POSTGRES_PASSWORD: brainydocs
      POSTGRES_DB: brainydocs
    networks:
      - brainydocs

networks:
  brainydocs:
